name: "📚 Latest Blogs"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout Repository"
        uses: actions/checkout@v4

      - name: "⚙️ Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "📚 Install & Run"
        run: |
          cd scripts
          npm install
          node update-blogs.js

      - name: "💾 Commit and Push"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/blogs.json README.md
          git commit -m "chore: update latest blog posts" || true
          git push
